"""
Django settings

Based on the one generated by 'django-admin startproject' using Django 3.0.7. and Django 3.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""
from dotenv import load_dotenv
import os

from decouple import config
from pathlib import Path

from django.contrib.messages import constants as messages

import mimetypes

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# load production server from .env
ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "").split(",")

CORS_ALLOWED_ORIGINS = os.getenv("CORS_ORIGIN", "").split(",")

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

csrf_origins = os.getenv('CSRF_TRUSTED_ORIGINS')
CSRF_TRUSTED_ORIGINS = csrf_origins.split(',') if csrf_origins else []

CELERY_ENABLED = config(
    "CELERY_ENABLED",
    default=False,
    cast=bool
)

CELERY_TASK_ALWAYS_EAGER = config(
    "CELERY_TASK_ALWAYS_EAGER",
    default=not CELERY_ENABLED,
    cast=bool
)

CELERY_TASK_EAGER_PROPAGATES = config(
    "CELERY_TASK_EAGER_PROPAGATES",
    default=not CELERY_ENABLED,
    cast=bool
)

if CELERY_ENABLED:
    CELERY_BROKER_URL = config("CELERY_BROKER_URL")
    CELERY_RESULT_BACKEND = config("CELERY_RESULT_BACKEND")

# Avisa o Django que o Ingress está recebendo HTTPS e mandando HTTP pro Pod
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Application definition

INSTALLED_APPS = [
    'corsheaders',
# Django Apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.admindocs',
# 3rd-party Apps
    'django_cpf_cnpj',
    'easyaudit',
    'polymorphic',
    'rest_framework', 
    'rest_framework.authtoken',
    'oauth2_provider',
    'drf_yasg',
    'behave_django',
# External Apps
# Local Apps
    'apps.classes',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'easyaudit.middleware.easyaudit.EasyAuditMiddleware',
]

ROOT_URLCONF = 'rai.urls'

CRISPY_TEMPLATE_PACK = 'bootstrap4'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join('templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'rai.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    { 'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator', },
]

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_L10N = True

USE_TZ = True

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATIC_URL = '/static/'

STATICFILES_DIRS = (os.path.join('static'), )

DATE_INPUT_FORMATS = ['%d/%m/%Y']

LOGIN_URL = "/accounts/login/"

LOGIN_REDIRECT_URL = '/'

LOGOUT_REDIRECT_URL = '/accounts/login'

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MESSAGE_LEVEL = 10

MESSAGE_TAGS = {
    messages.DEBUG: 'alert-info',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}

ERRORS_MESSAGES = {
    "unique":"Erro! Chave unica não pode se repetir"
}

MEDIA_URL = '/media/'

SHARED_UPLOADS_ROOT = os.getenv('SHARED_UPLOADS_ROOT', '/app/shared/uploads')
MEDIA_ROOT = os.path.join(SHARED_UPLOADS_ROOT, 'media')
try:
    # Attempt to create MEDIA_ROOT if possible. In some environments (CI, containers)
    # the process may not have permission to create directories under '/' (e.g. '/app').
    # Avoid raising an exception during settings import; log a warning instead.
    os.makedirs(MEDIA_ROOT, exist_ok=True)
except PermissionError:
    # Do not fail Django startup solely because we couldn't create the shared media dir.
    import logging
    logging.getLogger(__name__).warning(
        'Permission denied while creating MEDIA_ROOT "%s". Ensure SHARED_UPLOADS_ROOT is writable or set to a local path.',
        MEDIA_ROOT
    )

REST_FRAMEWORK = {
    'DATETIME_FORMAT': '%d/%m/%Y',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'PAGE_SIZE': 10,
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': ('oauth2_provider.contrib.rest_framework.OAuth2Authentication',),
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ]
}

OAUTH2_PROVIDER = {
    'SCOPES': {'read': 'Read scope', 'write': 'Write scope', 'groups': 'Access to your groups'},
    'ACCESS_TOKEN_EXPIRE_SECONDS': 36000,
}

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


EMAIL_HOST = config('EMAIL_HOST')
EMAIL_PORT = config('EMAIL_PORT')
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
EMAIL_USE_TLS = config('EMAIL_USE_TLS')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL')

URL_VALIDATION_SUCCESS = 'password_reset'
URL_VALIDATION_ERRO = 'validation_erro'

URL = config('URL')
URL_VALIDATION = config('URL_VALIDATION')

HASHIDS_SALT = config('HASHIDS_SALT')
AI_CONFIG_ENCRYPTION_KEY = config('AI_CONFIG_ENCRYPTION_KEY')

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,

    "root": {
        "level": "INFO",
        "handlers": ["console", "file"],
    },

    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "app",
        },
        "file": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "filename": "./logs/django.log",
            "formatter": "app",
        },
    },

    "loggers": {
        "django": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": True,
        },
        "apps": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": False,
        },
    },

    "formatters": {
        "app": {
            "format": (
                "%(asctime)s [%(levelname)s] "
                "%(name)s.%(funcName)s: %(message)s"
            ),
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
    },
}